#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto INSTALADO SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# FUL Debian 7 32 bit & 64 bit                  #"
echo -e "# MMMMMMMMMMMMMMSSSSSSCCCCCCCCCCCCCCCCCC    #"
echo -e "# LOS ~MSC~                                     #"
echo -e "#-----------------------------------------------#"
echo -e "PERU"
echo -e "---------"
echo -e "VPS FUL"
echo -e "Admin MSC"
echo -e "Google"
echo -e "LOS(MSC)"
echo -e ""
echo -e "FBI"
echo -e "----"
echo -e "grupo vip"
echo -e "msc"
echo -e "msc"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
