#!/bin/bash
echo -e ""
echo -e "COMANDOS         : INFO"
echo -e "" 
echo -e "Ⓜ️ MENU          : Muestra una lista de comandos disponibles"
echo -e "Ⓜ️ CREAR         : crear usuarios SSH & OpenVPN"
echo -e "Ⓜ️ PRUEVA        : crea User prueva"
echo -e "Ⓜ️ ELIMINAR      : eliminar user SSH & OpenVPN"
echo -e "Ⓜ️ ONLINE        : User online"
echo -e "Ⓜ️ LISTA         : lista usuarios SSH & OpenVPN"
echo -e "Ⓜ️ EXPIRADO      : eliminar User expirado"
echo -e "Ⓜ️ REINICIAR     : Reiniciar servicio dropbear,webmin"
echo -e "                   squid3, OpenVPN,Stunnel SSH"
echo -e "Ⓜ️ SPEEDTEST     : Speedtest VPS"
echo -e "Ⓜ️ INFO          : info del sistema"
echo -e "Ⓜ️ MAS           : Info del script"
echo -e "Ⓜ️ REBOOT        : Reiniciar VPS"
echo -e "Ⓜ️ EXIT          : salir del terminal SSH"
echo -e "=============~mscvip~"===================
echo -e ""
