#!/bin/bash
echo -e ""
echo -e "=============~MSCPERU=================#" 
echo -e "COMANDOS         : INFO DE LOS COMANDOS"
echo -e "" 
echo -e "Ⓜ️ MENU          : Muestra una lista de comandos disponibles"
echo -e "Ⓜ️ CREAR         : Crear usuarios SSH & OpenVPN"
echo -e "Ⓜ️ PRUEVA        : Crea Usuario de prueva"
echo -e "Ⓜ️ ELIMINAR      : Eliminar usuarios SSH & OpenVPN"
echo -e "Ⓜ️ ONLINE        : Usuarios online"
echo -e "Ⓜ️ LISTA         : Lista de usuarios SSH & OpenVPN"
echo -e "Ⓜ️ EXPIRADO      : Eliminar Usuarios expirado"
echo -e "Ⓜ️ REINICIAR     : Reiniciar servicio OpenSSH,dropbear,webmin"
echo -e "                   squid3,OpenVPN,SSL"
echo -e "Ⓜ️ VELOCIDAD     : Medir la velocidad de VPS"
echo -e "Ⓜ️ INFO          : Info del sistema"
echo -e "Ⓜ️ BMON          : permite ver en tiempo real su ancho de banda"
echo -e "Ⓜ️ MAS           : Info del script"
echo -e "Ⓜ️ REBOOT        : Reiniciar VPS"
echo -e "Ⓜ️ EXIT          : Salir del terminal SSH"
echo -e "Ⓜ️ ACTUALIZACION : Muestra informacion de la siguiente" 
echo -e "                   actualizacion del script" 
echo -e "=============~MSCPERU~================#"
echo -e ""
