#!/bin/bash
echo -e ""
echo -e "» menu          : Muestra una lista de comandos disponibles"
echo -e "» crear-user    : crear usuarios SSH & OpenVPN"
echo -e "» prueva        : crea User prueva"
echo -e "» user-del      : eliminar user SSH & OpenVPN"
echo -e "» user-onli     : User online"
echo -e "» user-list     : lista usuarios SSH & OpenVPN"
echo -e "» elexp         : eliminar User exportado"
echo -e "» resetear      : Resetear servicio dropbear, webmin"
echo -e "                 squid3, OpenVPN,Stunnel SSH"
echo -e "» reboot        : Reiniciar VPS"
echo -e "» speedtest     : Speedtest VPS"
echo -e "» info          : info del sistema"
echo -e "» about         : Info del script"
echo -e "» exit          : salir del terminal SSH"
echo -e "~msc vip~"
